### ISSUE TITLE
New librairies: regionmask, salem and climetlab

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#143]
Hi,

Could you add the following librairies:

- regionmask: https://regionmask.readthedocs.io/
- salem: https://salem.readthedocs.io/
- climetlab: https://climetlab.readthedocs.io/en/latest/

Thanks,
Matthieu.

**Comment by thebaptiste** [comment]
I will add regionmask and salem
For the time being we can't add climetlab because of a problem on it's dependency ecmwflibs. I have open this [issue](https://github.com/ecmwf/ecmwflibs/issues/2) on ECMWF Github for this problem, I hope it will be fixed soon.
climetlab and ecmwlibs are very "young" packages...

**Comment by thebaptiste** [comment]
There was a problem on source distribution of salem ([see issue here](https://github.com/fmaussion/salem/issues/187)) but thanks to @fmaussion, it was solved within a day.

**Comment by thebaptiste** [comment]
Still a problem on ecmwflibs, [PR 168](https://github.com/metwork-framework/mfextaddon_scientific/pull/168) doesn't build on CentOS6 in our continuous integration system (we build on CentOS6 with recent compilers to be compatible with most of the linux distributions).
I will probably add an other specific addon (mfextaddon_scientific_extra) to provide climetlab (built on CentOS7).
