### ISSUE TITLE
add batman python module

### ISSUE THREAD

**Issue by cauphilippe** [metwork-framework/mfextaddon_scientific#158]
hello,
I need
- the POD of batman for data reduction
- the surrogate model to interpolate intermediate forecasts ( RandomForestRegressor / ExtraTreesRegressor)

Is it possible to add the batman module ?
sincerely
Philippe Cau

**Comment by thebaptiste** [comment]
Not yet finished (integration tests are failing because of a dependency).

**Comment by thebaptiste** [comment]
It's ok now.
This new feature will be released in Metwork 1.1
Until then, it is possible to test it on integration or master branch.
I encourage you to do so, because in our integration tests we only checked `import batman` doesn't fail, which is not a guarantee that everything will work fine four your needs.
You can also provide us with a more relevant python script we could use for integration test.
