### ISSUE TITLE
Installation of Shiny

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#638]
Hi Metwork team

Would be great to have Shiny in the next version of MetWork (needs Faicons).

Thanks a lot
Cheers,
Matthieu Sorel

**Comment by thebaptiste** [comment]
Hi Matthieu

I added Shiny and Faicons in the master version of Metwork. They are available in a new layer, python3_extratools (the layer python3_scientific starting to be very big !).

By the way Faicons is only an optional dependency of Shiny. There are many other optional dependencies, some provided by Metwork (astropy, seaborn, pandas, matplotlib, polars, numpy, plotly, geopandas, scikit-learn, folium...), others not (see [here](https://github.com/posit-dev/py-shiny/blob/v1.0.0/setup.cfg)). Some of them might be useful for you, let me know.

I would by interested by one or two examples of what you want to do with shiny, in order to add integration tests. For the time being my only test is to check that `import shiny` and `import faicons` are ok.

Cheers

**Comment by thebaptiste** [comment]
Closed by #648 and #652
