### ISSUE TITLE
add metview component (built without ui support)

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfextaddon_scientific#66]
As discussed this morning with ECMWF, there is a dedicated option to build metview without ui support. So it would be interesting to have metview support in metwork

**Comment by iainrussell** [comment]
So, for this to work, you need to build Magics with the CMake flag -DMETVIEW_NO_QT=ON.
Then you can build Metview with the flag -DENABLE_UI=OFF

**Comment by thebaptiste** [comment]
Thanks Iain, it's in progress. I had a compilation problem because the eccodes release used so far in Metwork (2.13.0) was not compatible with the last Metview release but an upgrade of eccodes will probably solve it.

**Comment by thebaptiste** [comment]
By the way it would be nice if Metview build checked eccodes release !

**Comment by thebaptiste** [comment]
Done.
Because of the particularities of the Metwork reduced build environment, several features have been disabled (see below). We can consider adding some of them later if required.

The following features have been enabled:
* TESTS , MetviewMiniBundle: Enable the unit tests
 * ECKIT_CMD , eckit: Utilities for administration tools
 * ECKIT_SQL , eckit: An SQL engine
 * BZIP2 , eckit: BZip2 support for compression
 * SSL , eckit: OpenSSL support
 * CURL , eckit: Curl library for transfering data with URLs
 * ATLAS_RUN , atlas: Use atlas/tools/atlas-run to run atlas tests
 * PKGCONFIG , atlas: Atlas pkgconfig
 * MIR_DOWNLOAD_MASKS , mir: download LSM files
 * TEST_ASSERTIONS , mir: test: regressions
 * OMP , atlas: support for OpenMP shared memory parallelism, mir: support for OpenMP shared memory parallelism
 * MPI , eckit: Use system MPI libraries, mir: support for MPI distributed parallelism
 * NETCDF , mir: support for NetCDF4, mars_client: support for NetCDF
 * PPROC_MIR , mars_client: compile with MIR interpolation

The following features have been disabled:
* EXPOSE_SUBPACKAGES , MetviewMiniBundle: Allow separate use of the sub-packages in the bundle
 * EXPERIMENTAL , eckit: Experimental features that havent graduated to production ready code
 * SANDBOX , eckit: Experimental features that havent graduated to production ready code, atlas: Build the sandbox stuff
 * EIGEN , eckit: Eigen linear algebra library, atlas: Use Eigen linear algebra library
 * RADOS , eckit: Ceph/Rados storage support
 * ARMADILLO , eckit: Armadillo linear algebra library
 * MKL , eckit: MKL linear algebra library
 * SNAPPY , eckit: Snappy support for compression
 * LZ4 , eckit: LZ4 support for compression
 * AEC , eckit: AEC support for compression
 * LAPACK , eckit: Linear Algebra PACKage
 * XXHASH , eckit: Use xxHash for non-crypto hashing in data integrity checks
 * JEMALLOC , eckit: Link against jemalloc memory allocator
 * CUDA , eckit: CUDA GPU linear algebra operations
 * VIENNACL , eckit: ViennaCL OpenCL linear algebra operations
 * EXTRA_TESTS , eckit: Add additional unit/performance tests
 * DOCS , eckit: Generate reference documentation, atlas: Atlas documentation
 * FORTRAN , atlas: Provide Fortran bindings
 * OMP_Fortran , atlas: support for Fortran OpenMP shared memory parallelism
 * OMP_CXX , atlas: support for CXX OpenMP shared memory parallelism
 * FFTW , atlas: Support for fftw
 * TRANS , atlas: Support for spectral transforms
 * TESSELATION , atlas: Support for unstructured mesh generation
 * GRIDTOOLS_STORAGE , atlas: Arrays internally use GridTools storage layer
 * ACC , atlas: OpenACC capable data structures
 * PROJ , atlas: PROJ-based projections
 * BOUNDSCHECKING , atlas: Bounds checking for atlas::ArrayView and atlas::IndexView
 * INIT_SNAN , atlas: Initialise atlas arrays with signaling_NaN (real types) or other invalid values (other types)
 * CLANG_TIDY , atlas: Use clang-tidy
 * INCLUDE_WHAT_YOU_USE , atlas: Use include-what-you-use clang-tool
 * ACCEPTANCE_TESTS , atlas:
 * MIR_TOOLS , mir: install mir tools
 * PNG , mir: support for PNG encoding
 * UDP_STATS , mars_client: Send statistics over UDP
 * PPROC_EMOS , mars_client: compile with EMOSLIB interpolation
 * BUFR_TOOLS , mars_client: compile BUFR tools
 * ODB , mars_client: compile with ODB support
 * MARS_USER_ENVIRONMENT , mars_client: Mars user will be in $MARS_USER
 * ODBDIRECT , mars_client: compile with ODB direct support
 * FDB , mars_client: support for FDB
 * FDB5 , mars_client: support for FDB5
 * ECMWF_DEVELOPMENT , mars_client: Special mode for development, activates ECMWF but deactivates auth, ems and schedule

**Comment by thefab** [comment]
ping @iainrussell @StephanSiemen

it's done: metview is in metwork unstable branch :-)

**Comment by iainrussell** [comment]
That's great @thebaptiste and @thefab !  Looking at the list of disabled features, it all looks fine to me. Well done and thanks for doing it! I'll have a look at which version of ecCodes Metview requires and make sure that CMake knows about the dependency.
Cheers!
Iain
